server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: vacationModule
          uri: http://localhost:8081/
          predicates:
            - Path=/vacation/**
        - id: financialModule
          uri: http://localhost:8082/
          predicates:
            - Path=/financial/**