version: '3.8'
services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-root}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
            - ./database:/docker-entrypoint-initdb.d/
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - postgres
        restart: unless-stopped
    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin
        ports:
            - "9411:9411"
        networks:
            - project-monitor
    discovery:
        image: faltfe/project-monitor-discovery
        build:
            context: ./discovery-service
        container_name: discovery
        profiles:
            - application
        restart: unless-stopped
        ports:
            - "8761:8761"
        networks:
            - project-monitor
    gateway:
        image: faltfe/project-monitor-gateway
        build:
            context: ./gateway
        container_name: gateway
        profiles:
            - application
        environment:
            - JAVA_OPTS=
                -DEUREKA_SERVER=http://discovery:8761/eureka
        restart: unless-stopped
        ports:
            - "8080:8080"
        depends_on:
            discovery:
                condition: service_healthy
        networks:
            - project-monitor
    vacation-monitor:
        image: faltfe/project-monitor-vacation-monitor
        build:
            context: ./vacation-monitor
        container_name: vacation-monitor
        profiles:
            - services
        environment:
            - JAVA_OPTS=
                -DEUREKA_SERVER=http://discovery:8761/eureka
        restart: on-failure
        ports:
            - "8081:8081"
        depends_on:
            gateway:
                condition: service_healthy
            postgres:
                condition: service_healthy
        networks:
            - project-monitor
            - postgres
    financial-monitor:
        image: faltfe/project-monitor-financial-monitor
        build:
            context: ./financial-monitor
        container_name: financial-monitor
        profiles:
            - services
        environment:
            - JAVA_OPTS=
                -DEUREKA_SERVER=http://discovery:8761/eureka
        restart: on-failure
        ports:
            - "8082:8082"
        depends_on:
            gateway:
                condition: service_healthy
            postgres:
                condition: service_healthy
        networks:
            - project-monitor
            - postgres
networks:
    project-monitor:
        driver: bridge
    postgres:
        driver: bridge

volumes:
    postgres:
    pgadmin:
