server:
    port: 8081
spring:
    application:
        name: project-monitor
    datasource:
        username: ${POSTGRES_USER:root}
        password: ${POSTGRES_PASSWORD:password}
        url: jdbc:postgresql://localhost:5432/vacation-service
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                generate_statistics: true
                jdbc:
                    time_zone: UTC
        show-sql: true
    main:
        banner-mode: 'off'
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
