server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: vacationModule
          uri: lb://project-monitor
          predicates:
            - Path=/vacation/**
        - id: financialModule
          uri: lb://finanical-monitor
          predicates:
            - Path=/financial/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka