server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: vacationModule
          uri: lb://vacation-monitor
          predicates:
            - Path=/vacation/**
        - id: financialModule
          uri: lb://financial-monitor
          predicates:
            - Path=/financial/**
eureka:
  client:
    serviceUrl:
        defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
