# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Financial Monitor

on: [push, pull_request ]

defaults:
  run:
    working-directory: server/financial-monitor

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJdk 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  
    - name: Build and test with Maven
      run: mvn -B verify
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./target/site/jacoco
        file: ./jacoco.xml
        flags: financial-monitor
        verbose: true
