# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Webclient

on:
  push:
    branches: [master]
    paths:
      - "webclient/**"
  pull_request:
    branches: [master]
    types: [opened, synchronize, closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
        working-directory: webclient
      - name: Run unit test
        run: npm run test
        working-directory: webclient
      - name: Run linter
        run: npm run lint
        working-directory: webclient
      - name: Cypress run
        run: npm run cypress:ci
        working-directory: webclient
        

    
